import { BodyPart } from '../types/clinical';

export interface BodyPartMapping {
  code: BodyPart;
  displayName: string;
  snomedCode: string;
  snomedDisplay: string;
  region: BodyRegion;
  dicomCode?: string;
}

export enum BodyRegion {
  HEAD_NECK = 'HEAD_NECK',
  SPINE = 'SPINE',
  CHEST_THORAX = 'CHEST_THORAX',
  ABDOMEN_PELVIS = 'ABDOMEN_PELVIS',
  UPPER_EXTREMITY = 'UPPER_EXTREMITY',
  LOWER_EXTREMITY = 'LOWER_EXTREMITY',
  WHOLE_BODY = 'WHOLE_BODY',
  VASCULAR = 'VASCULAR',
}

export const BODY_PART_MAPPINGS: Record<BodyPart, BodyPartMapping> = {
  [BodyPart.HEAD]: {
    code: BodyPart.HEAD,
    displayName: 'Head',
    snomedCode: '69536005',
    snomedDisplay: 'Head structure (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'HEAD',
  },
  [BodyPart.BRAIN]: {
    code: BodyPart.BRAIN,
    displayName: 'Brain',
    snomedCode: '12738006',
    snomedDisplay: 'Brain structure (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'BRAIN',
  },
  [BodyPart.NECK]: {
    code: BodyPart.NECK,
    displayName: 'Neck',
    snomedCode: '45048000',
    snomedDisplay: 'Neck structure (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'NECK',
  },
  [BodyPart.CERVICAL_SPINE]: {
    code: BodyPart.CERVICAL_SPINE,
    displayName: 'Cervical Spine',
    snomedCode: '122494005',
    snomedDisplay: 'Cervical spine structure (body structure)',
    region: BodyRegion.SPINE,
    dicomCode: 'CSPINE',
  },
  [BodyPart.THORACIC_SPINE]: {
    code: BodyPart.THORACIC_SPINE,
    displayName: 'Thoracic Spine',
    snomedCode: '122495006',
    snomedDisplay: 'Thoracic spine structure (body structure)',
    region: BodyRegion.SPINE,
    dicomCode: 'TSPINE',
  },
  [BodyPart.LUMBAR_SPINE]: {
    code: BodyPart.LUMBAR_SPINE,
    displayName: 'Lumbar Spine',
    snomedCode: '122496007',
    snomedDisplay: 'Lumbar spine structure (body structure)',
    region: BodyRegion.SPINE,
    dicomCode: 'LSPINE',
  },
  [BodyPart.CHEST]: {
    code: BodyPart.CHEST,
    displayName: 'Chest',
    snomedCode: '51185008',
    snomedDisplay: 'Thoracic structure (body structure)',
    region: BodyRegion.CHEST_THORAX,
    dicomCode: 'CHEST',
  },
  [BodyPart.ABDOMEN]: {
    code: BodyPart.ABDOMEN,
    displayName: 'Abdomen',
    snomedCode: '818983003',
    snomedDisplay: 'Abdomen (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'ABDOMEN',
  },
  [BodyPart.PELVIS]: {
    code: BodyPart.PELVIS,
    displayName: 'Pelvis',
    snomedCode: '12921003',
    snomedDisplay: 'Pelvis structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'PELVIS',
  },
  [BodyPart.ABDOMEN_PELVIS]: {
    code: BodyPart.ABDOMEN_PELVIS,
    displayName: 'Abdomen and Pelvis',
    snomedCode: '818983003',
    snomedDisplay: 'Abdomen and pelvis structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'ABDOMENPELVIS',
  },
  [BodyPart.SHOULDER]: {
    code: BodyPart.SHOULDER,
    displayName: 'Shoulder',
    snomedCode: '16982005',
    snomedDisplay: 'Shoulder region structure (body structure)',
    region: BodyRegion.UPPER_EXTREMITY,
    dicomCode: 'SHOULDER',
  },
  [BodyPart.UPPER_ARM]: {
    code: BodyPart.UPPER_ARM,
    displayName: 'Upper Arm (Humerus)',
    snomedCode: '40983000',
    snomedDisplay: 'Upper arm structure (body structure)',
    region: BodyRegion.UPPER_EXTREMITY,
    dicomCode: 'HUMERUS',
  },
  [BodyPart.ELBOW]: {
    code: BodyPart.ELBOW,
    displayName: 'Elbow',
    snomedCode: '76248009',
    snomedDisplay: 'Elbow region structure (body structure)',
    region: BodyRegion.UPPER_EXTREMITY,
    dicomCode: 'ELBOW',
  },
  [BodyPart.FOREARM]: {
    code: BodyPart.FOREARM,
    displayName: 'Forearm',
    snomedCode: '14975008',
    snomedDisplay: 'Forearm structure (body structure)',
    region: BodyRegion.UPPER_EXTREMITY,
    dicomCode: 'FOREARM',
  },
  [BodyPart.WRIST]: {
    code: BodyPart.WRIST,
    displayName: 'Wrist',
    snomedCode: '8205005',
    snomedDisplay: 'Wrist region structure (body structure)',
    region: BodyRegion.UPPER_EXTREMITY,
    dicomCode: 'WRIST',
  },
  [BodyPart.HAND]: {
    code: BodyPart.HAND,
    displayName: 'Hand',
    snomedCode: '85562004',
    snomedDisplay: 'Hand structure (body structure)',
    region: BodyRegion.UPPER_EXTREMITY,
    dicomCode: 'HAND',
  },
  [BodyPart.HIP]: {
    code: BodyPart.HIP,
    displayName: 'Hip',
    snomedCode: '24136001',
    snomedDisplay: 'Hip region structure (body structure)',
    region: BodyRegion.LOWER_EXTREMITY,
    dicomCode: 'HIP',
  },
  [BodyPart.UPPER_LEG]: {
    code: BodyPart.UPPER_LEG,
    displayName: 'Upper Leg (Femur)',
    snomedCode: '68367000',
    snomedDisplay: 'Thigh structure (body structure)',
    region: BodyRegion.LOWER_EXTREMITY,
    dicomCode: 'FEMUR',
  },
  [BodyPart.KNEE]: {
    code: BodyPart.KNEE,
    displayName: 'Knee',
    snomedCode: '72696002',
    snomedDisplay: 'Knee region structure (body structure)',
    region: BodyRegion.LOWER_EXTREMITY,
    dicomCode: 'KNEE',
  },
  [BodyPart.LOWER_LEG]: {
    code: BodyPart.LOWER_LEG,
    displayName: 'Lower Leg (Tibia/Fibula)',
    snomedCode: '30021000',
    snomedDisplay: 'Lower leg structure (body structure)',
    region: BodyRegion.LOWER_EXTREMITY,
    dicomCode: 'LEG',
  },
  [BodyPart.ANKLE]: {
    code: BodyPart.ANKLE,
    displayName: 'Ankle',
    snomedCode: '70258002',
    snomedDisplay: 'Ankle region structure (body structure)',
    region: BodyRegion.LOWER_EXTREMITY,
    dicomCode: 'ANKLE',
  },
  [BodyPart.FOOT]: {
    code: BodyPart.FOOT,
    displayName: 'Foot',
    snomedCode: '56459004',
    snomedDisplay: 'Foot structure (body structure)',
    region: BodyRegion.LOWER_EXTREMITY,
    dicomCode: 'FOOT',
  },
  [BodyPart.WHOLE_BODY]: {
    code: BodyPart.WHOLE_BODY,
    displayName: 'Whole Body',
    snomedCode: '38266002',
    snomedDisplay: 'Entire body (body structure)',
    region: BodyRegion.WHOLE_BODY,
    dicomCode: 'WHOLEBODY',
  },
  [BodyPart.BREAST]: {
    code: BodyPart.BREAST,
    displayName: 'Breast',
    snomedCode: '76752008',
    snomedDisplay: 'Breast structure (body structure)',
    region: BodyRegion.CHEST_THORAX,
    dicomCode: 'BREAST',
  },
  [BodyPart.HEART]: {
    code: BodyPart.HEART,
    displayName: 'Heart',
    snomedCode: '80891009',
    snomedDisplay: 'Heart structure (body structure)',
    region: BodyRegion.CHEST_THORAX,
    dicomCode: 'HEART',
  },
  [BodyPart.ORBIT]: {
    code: BodyPart.ORBIT,
    displayName: 'Orbit',
    snomedCode: '363654007',
    snomedDisplay: 'Structure of orbit (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'ORBIT',
  },
  [BodyPart.SINUSES]: {
    code: BodyPart.SINUSES,
    displayName: 'Sinuses',
    snomedCode: '2095001',
    snomedDisplay: 'Paranasal sinus structure (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'SINUS',
  },
  [BodyPart.TEMPORAL_BONES]: {
    code: BodyPart.TEMPORAL_BONES,
    displayName: 'Temporal Bones',
    snomedCode: '60911003',
    snomedDisplay: 'Temporal bone structure (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'TEMPORAL',
  },
  [BodyPart.FACE]: {
    code: BodyPart.FACE,
    displayName: 'Face',
    snomedCode: '89545001',
    snomedDisplay: 'Face structure (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'FACE',
  },
  [BodyPart.MANDIBLE]: {
    code: BodyPart.MANDIBLE,
    displayName: 'Mandible',
    snomedCode: '91609006',
    snomedDisplay: 'Mandible structure (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'MANDIBLE',
  },
  [BodyPart.SACRUM]: {
    code: BodyPart.SACRUM,
    displayName: 'Sacrum',
    snomedCode: '54735007',
    snomedDisplay: 'Sacral vertebral column structure (body structure)',
    region: BodyRegion.SPINE,
    dicomCode: 'SSPINE',
  },
  [BodyPart.COCCYX]: {
    code: BodyPart.COCCYX,
    displayName: 'Coccyx',
    snomedCode: '64688005',
    snomedDisplay: 'Coccygeal structure (body structure)',
    region: BodyRegion.SPINE,
    dicomCode: 'COCCYX',
  },
  [BodyPart.RIBS]: {
    code: BodyPart.RIBS,
    displayName: 'Ribs',
    snomedCode: '113197003',
    snomedDisplay: 'Rib structure (body structure)',
    region: BodyRegion.CHEST_THORAX,
    dicomCode: 'RIBS',
  },
  [BodyPart.STERNUM]: {
    code: BodyPart.STERNUM,
    displayName: 'Sternum',
    snomedCode: '56873002',
    snomedDisplay: 'Sternum structure (body structure)',
    region: BodyRegion.CHEST_THORAX,
    dicomCode: 'STERNUM',
  },
  [BodyPart.CLAVICLE]: {
    code: BodyPart.CLAVICLE,
    displayName: 'Clavicle',
    snomedCode: '51299004',
    snomedDisplay: 'Clavicle structure (body structure)',
    region: BodyRegion.UPPER_EXTREMITY,
    dicomCode: 'CLAVICLE',
  },
  [BodyPart.SCAPULA]: {
    code: BodyPart.SCAPULA,
    displayName: 'Scapula',
    snomedCode: '79601000',
    snomedDisplay: 'Scapula structure (body structure)',
    region: BodyRegion.UPPER_EXTREMITY,
    dicomCode: 'SCAPULA',
  },
  [BodyPart.THYROID]: {
    code: BodyPart.THYROID,
    displayName: 'Thyroid',
    snomedCode: '69748006',
    snomedDisplay: 'Thyroid gland structure (body structure)',
    region: BodyRegion.HEAD_NECK,
    dicomCode: 'THYROID',
  },
  [BodyPart.LIVER]: {
    code: BodyPart.LIVER,
    displayName: 'Liver',
    snomedCode: '10200004',
    snomedDisplay: 'Liver structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'LIVER',
  },
  [BodyPart.KIDNEY]: {
    code: BodyPart.KIDNEY,
    displayName: 'Kidney',
    snomedCode: '64033007',
    snomedDisplay: 'Kidney structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'KIDNEY',
  },
  [BodyPart.PANCREAS]: {
    code: BodyPart.PANCREAS,
    displayName: 'Pancreas',
    snomedCode: '15776009',
    snomedDisplay: 'Pancreas structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'PANCREAS',
  },
  [BodyPart.SPLEEN]: {
    code: BodyPart.SPLEEN,
    displayName: 'Spleen',
    snomedCode: '78961009',
    snomedDisplay: 'Spleen structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'SPLEEN',
  },
  [BodyPart.GALLBLADDER]: {
    code: BodyPart.GALLBLADDER,
    displayName: 'Gallbladder',
    snomedCode: '28231008',
    snomedDisplay: 'Gallbladder structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'GALLBLADDER',
  },
  [BodyPart.BLADDER]: {
    code: BodyPart.BLADDER,
    displayName: 'Urinary Bladder',
    snomedCode: '89837001',
    snomedDisplay: 'Urinary bladder structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'BLADDER',
  },
  [BodyPart.PROSTATE]: {
    code: BodyPart.PROSTATE,
    displayName: 'Prostate',
    snomedCode: '41216001',
    snomedDisplay: 'Prostate structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'PROSTATE',
  },
  [BodyPart.UTERUS]: {
    code: BodyPart.UTERUS,
    displayName: 'Uterus',
    snomedCode: '35039007',
    snomedDisplay: 'Uterus structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'UTERUS',
  },
  [BodyPart.OVARY]: {
    code: BodyPart.OVARY,
    displayName: 'Ovary',
    snomedCode: '15497006',
    snomedDisplay: 'Ovary structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'OVARY',
  },
  [BodyPart.TESTICLE]: {
    code: BodyPart.TESTICLE,
    displayName: 'Testicle',
    snomedCode: '40689003',
    snomedDisplay: 'Testis structure (body structure)',
    region: BodyRegion.ABDOMEN_PELVIS,
    dicomCode: 'TESTICLE',
  },
  [BodyPart.AORTA]: {
    code: BodyPart.AORTA,
    displayName: 'Aorta',
    snomedCode: '15825003',
    snomedDisplay: 'Aortic structure (body structure)',
    region: BodyRegion.VASCULAR,
    dicomCode: 'AORTA',
  },
  [BodyPart.CAROTID]: {
    code: BodyPart.CAROTID,
    displayName: 'Carotid Arteries',
    snomedCode: '69105007',
    snomedDisplay: 'Carotid artery structure (body structure)',
    region: BodyRegion.VASCULAR,
    dicomCode: 'CAROTID',
  },
  [BodyPart.EXTREMITY_VEINS]: {
    code: BodyPart.EXTREMITY_VEINS,
    displayName: 'Extremity Veins',
    snomedCode: '29092000',
    snomedDisplay: 'Vein structure of extremity (body structure)',
    region: BodyRegion.VASCULAR,
    dicomCode: 'EXTREMITYVEIN',
  },
  [BodyPart.EXTREMITY_ARTERIES]: {
    code: BodyPart.EXTREMITY_ARTERIES,
    displayName: 'Extremity Arteries',
    snomedCode: '11527006',
    snomedDisplay: 'Artery structure of extremity (body structure)',
    region: BodyRegion.VASCULAR,
    dicomCode: 'EXTREMITYARTERY',
  },
};

/**
 * Get body parts by region.
 */
export function getBodyPartsByRegion(region: BodyRegion): BodyPartMapping[] {
  return Object.values(BODY_PART_MAPPINGS).filter((bp) => bp.region === region);
}

/**
 * Look up a body part mapping by SNOMED code.
 */
export function getBodyPartBySNOMED(snomedCode: string): BodyPartMapping | undefined {
  return Object.values(BODY_PART_MAPPINGS).find((bp) => bp.snomedCode === snomedCode);
}

/**
 * Look up a body part mapping by DICOM code.
 */
export function getBodyPartByDICOM(dicomCode: string): BodyPartMapping | undefined {
  return Object.values(BODY_PART_MAPPINGS).find(
    (bp) => bp.dicomCode?.toUpperCase() === dicomCode.toUpperCase(),
  );
}
